---

- name: Restart RabbitMQ service
  service:
    name: "{{ rabbitmq_service }}"
    state: restarted
  when: >
    rabbitmq_service_started is not defined or
    not rabbitmq_service_started.changed
